### ISSUE TITLE
Font size/clarity

### ISSUE THREAD

**Issue by grahamperrin** [jvillalobos/latest-on-amo#1]
We [like Fridays](https://github.com/mozilla/addons/issues/11129) ❤️ 

Compared to (for example) the History sidebar – 

![2018-02-04 21 18 37 waterfox](https://user-images.githubusercontent.com/192271/35782529-1c9f91fa-09f1-11e8-8bb1-93e093b5aab9.png)

– there's something _not quite_ right about the font in version 0.8 of Latest on AMO: 

![2018-02-04 21 05 01 waterfox](https://user-images.githubusercontent.com/192271/35782501-d67e57a6-09f0-11e8-8720-d4e4378aa56c.png)

Is it fractionally smaller than a norm? Or somehow not anti-aliasing as it should? 

Shots above are from Waterfox on FreeBSD-CURRENT, I followed up with a check in Firefox Quantum 58.0; the font appears the same. Sorry if my use of Scrollmap makes your eyes bleed. 

Yours sincerely, specifically and concisely, 
Graham

**Comment by jvillalobos** [comment]
The summary text has a 85% size set so each entry won't take too much room. Is that the only one you see problems for, or do you think the add-on name also looks strange?

**Comment by grahamperrin** [comment]
Apologies for the late reply. 

The size for the name is ideal. 

The two sizes below are too small. 

Broader context, with a browser preference for _sans-serif_ 16 (16 seems to be an OOTB default): 

![2018-02-22 00 39 53](https://user-images.githubusercontent.com/192271/36513849-91e9318e-1769-11e8-83b0-c955b0dae008.png)

(Ignore the absence of the scrollbar. That's a transient issue, not a bug in your extension.)

I wonder … how might the descriptive paragraph appear at 100% with a narrow font?
